### ISSUE TITLE
Maybe a change to the startup that checks to see if Click Lock is active in Control Panel

### ISSUE THREAD

**Issue by Diez66** [mmikeww/ClickLock-Indicator#1]
OK, first off, I love this.
I play a game where Click Lock is really useful and it does work perfectly and has made this easier so Thanks.

I decided to make it start automatically on windows startup.

I get the message "Clicklock is not enable in the Control Panel"
Exiting.

So, first off, I do not want to break it and wondered if this is something that was changeable.
¿Maybe I can simply delete lines 8 through to 13??

Anyway, if this check is vital, I will live with it or maybe try to workout something.

Thank you for this simple bit of code, that I could not have written.

**Comment by mmikeww** [comment]
Line 10 is what turns on the left mouse button hotkey, so you would want to keep that line in there

I wonder what is happening.. Maybe this AHK script is launching first, before Windows turns on ClickLock? Its been a while since I tested this, does ClickLock stay on after a reboot? Or do you have to turn it back on with each restart?

If you remove lines 8-13 but keep line 10, does everything work properly at startup?

**Comment by Diez66** [comment]
OK, that seems to work, it now runs on startup.
I did make a typo by adding a random character on what became line 22 for some random reason, but I was able to work that out.

So, unless when I get to use in anger later today anything pops, Result!!, Thank you.

I would have so lost line 10 as well so I will come back and close later or you can.

Thanks again, it is a really useful script.

**Comment by Diez66** [comment]
OK, so I have played with this and it is happy to start with Windows startup.
Also, if Clicklock is not active I can start it happily.

Thank you for the super quick support.

I did remove the lines you suggested, leaving line 10 in place.
